layout_spectrum: 0.9049408
typography_spectrum: 0.5129345
color:
  saturation: 0.5835813
  brandStrength: 0.705416
  lightness: 0.8039742
  rhythmicContrast: 0.5022233
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: franksilverawritersworkshop2
